DATASET:
  root_dataset: "./data/"
  list_train: "./data/training.odgt"
  list_val: "./data/validation.odgt"
  num_class: 6
  imgSizes: (1000,)
  imgMaxSize: 6528
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True

MODEL:
  arch_encoder: "hrnetv2"
  arch_decoder: "c1"
  fc_dim: 720

TRAIN:
  batch_size_per_gpu: 3
  num_epoch: 30
  start_epoch: 12
  epoch_iters: 6500
  optim: "SGD"
  lr_encoder: 0.0001
  lr_decoder: 0.0001
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 0.0005
  deep_sup_scale: 0.4
  fix_bn: True
  workers: 16
  disp_iter: 20
  seed: 306

VAL:
  visualize: False
  checkpoint: "epoch_12.pth"

TEST:
  checkpoint: "epoch_22.pth"
  result: "./"

DIR: "ckpt/ade20k-hrnetv2-CROp"