DATASET:
    root_dataset: "./data/"
    list_train: "./data/training.odgt"
    list_val: "./data/validation.odgt"
    num_class: 6
    imgSizes: (1000,)
    imgMaxSize: 6528
    padding_constant: 8
    segm_downsampling_rate: 8
    random_flip: True
  
MODEL:
    arch_encoder: "shufflenetv2"
    arch_decoder: "SwiftNet"
    fc_dim: 464

TRAIN:
    batch_size_per_gpu: 8
    num_epoch: 20
    start_epoch: 2
    epoch_iters: 2438
    optim: "SGD"
    lr_encoder: 0.0003
    lr_decoder: 0.0003
    lr_pow: 0.9
    beta1: 0.9
    weight_decay: 0.0
    deep_sup_scale: 0.4
    fix_bn: False
    workers: 16
    disp_iter: 20
    seed: 306

VAL:
    visualize: True
    checkpoint: "epoch_2.pth"

TEST:
    checkpoint: "epoch_22.pth"
    result: "./"

DIR: "ckpt/shuffle"